package com.module.autographs.carmanufacturing.microservice.util;

public class Constants {

    // HTTP STATUS CODES
    public static final String HTTP_RESPONSE_CODE_OK = "200";
    public static final String HTTP_RESPONSE_CODE_INTERNAL_SERVER_ERROR = "500";

    // ALL API PATHS

    // 1 - NEW CAR MANUFACTURING
    public static final String NEW_CAR_MANUFACTURING_GET_API_PATH = "/getAllNewCarManufacturingData";
    public static final String NEW_CAR_MANUFACTURING_POST_API_PATH = "/addNewCarManufacturingData";
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_API_PATH = "/deleteAllNewCarManufacturingData";

    // 2 - NEW CAR MANUFACTURING BY TYPE
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_GET_API_PATH = "/getAllNewCarManufacturingByTypeData";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_POST_API_PATH = "/addNewCarManufacturingByTypeData";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_API_PATH = "/deleteAllNewCarManufacturingByTypeData";


    // ALL SWAGGER CONSTANTS BELOW ---------------------------------------------------------------------------------------------------------

    // 1 - NEW CAR MANUFACTURING
    // GET API
    public static final String NEW_CAR_MANUFACTURING_GET_SUMMARY = "GET - NEW CAR MANUFACTURING DATA";
    public static final String NEW_CAR_MANUFACTURING_SUCCESS = "NEW CAR MANUFACTURING DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR MANUFACTURING.";
    // POST API
    public static final String NEW_CAR_MANUFACTURING_POST_SUMMARY = "POST - ADD NEW CAR MANUFACTURING";
    public static final String NEW_CAR_MANUFACTURING_ADD_SUCCESS = "NEW CAR MANUFACTURING DATA ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR MANUFACTURING DATA.";
    // DELETE API
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR MANUFACTURING DATA";
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_SUCCESS = "NEW CAR MANUFACTURING DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR MANUFACTURING DATA.";

    // 2 - NEW CAR MANUFACTURING BY TYPE
    // GET API
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_GET_SUMMARY = "GET - NEW CAR MANUFACTURING BY TYPE DATA";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_SUCCESS = "NEW CAR MANUFACTURING BY TYPE DATA FETCHED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_NO_DATA_FOUND = "NO DATA FOUND FOR NEW CAR MANUFACTURING BY TYPE.";
    // POST API
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_POST_SUMMARY = "POST - ADD NEW CAR MANUFACTURING BY TYPE";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_ADD_SUCCESS = "NEW CAR MANUFACTURING DATA BY TYPE ADDED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_ADD_FAILURE = "FAILURE OCCURRED WHILE ADDING NEW CAR MANUFACTURING BY TYPE DATA.";
    // DELETE API
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_SUMMARY = "DELETE ALL - NEW CAR MANUFACTURING BY TYPE  DATA";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_SUCCESS = "NEW CAR MANUFACTURING BY TYPE DATA DELETED SUCCESSFULLY.";
    public static final String NEW_CAR_MANUFACTURING_BY_TYPE_DELETE_ALL_FAILURE = "FAILURE OCCURRED WHILE DELETING NEW CAR MANUFACTURING BY TYPE DATA.";

}
